# For more information on configuring this file refer to
# https://gitversion.net/docs/reference/configuration

mode: ContinuousDeployment
branches:
  feature:
    tag: beta
  main: {}
ignore:
  sha: []